### ISSUE TITLE
Compatibility with Graphic BLOB fields

### ISSUE THREAD

**Issue by PhoneixS** [leonhad/paradoxdriver#10]
Trying to use the driver I have come to an exception:

Exception in thread "main" java.sql.SQLException: Type not found: 16
	at com.googlecode.paradox.results.ParadoxFieldType.getSQLTypeByType(ParadoxFieldType.java:155)
	at com.googlecode.paradox.metadata.ParadoxField.getSqlType(ParadoxField.java:214)
	at com.googlecode.paradox.metadata.ParadoxField.setSize(ParadoxField.java:331)
	at com.googlecode.paradox.data.TableData.parseTableFields(TableData.java:258)
	at com.googlecode.paradox.data.TableData.loadTableHeader(TableData.java:223)
	at com.googlecode.paradox.data.TableData.listTables(TableData.java:95)
	at com.googlecode.paradox.planner.Planner.createSelect(Planner.java:124)
	at com.googlecode.paradox.planner.Planner.create(Planner.java:107)
	at com.googlecode.paradox.ParadoxStatement.executeSelect(ParadoxStatement.java:236)
	at com.googlecode.paradox.ParadoxStatement.execute(ParadoxStatement.java:174)
	at com.penalara.ghcimpex.ies2000.App.main(App.java:29)

I have searched and found that is a Graphic BLOB field as it's also specified in the file format from http://www.randybeck.com/paradoxformat.shtml.

```
|      |           fType  fSize(decimal)                                     |
|      |           -------------------------                                 |
|      |            $01     v   "A"  Alpha                                   |
|      |            $02     4   "D"  Date                                    |
|      |            $03     2   "S"  Short integer                           |
|      |            $04     4   "I"  Long integer                            |
|      |            $05     8   "$"  currency                                |
|      |            $06     8   "N"  Number                                  |
|      |            $09     1   "L"  Logical                                 |
|      |            $0C     v   "M"  Memo BLOb                               |
|      |            $0D     v   "B"  Binary Large Object                     |
|      |            $0E     v   "F"  Formatted Memo BLOb                     |
|      |            $0F     v   "O"  OLE                                     |
|      |            $10     v   "G"  Graphic BLOb                            |
|      |            $14     4   "T"  Time                                    |
|      |            $15     8   "@"  Timestamp                               |
|      |            $16     4   "+"  Autoincrement                           |
|      |            $17    17*  "#"  BCD                                     |
|      |            $18     v   "Y"  Bytes
```

I don't really use this field but you can't read the data as the exception interrupt the process of listing tables. For me is enough if it would be ignored or read as binary data.

**Comment by PhoneixS** [comment]
This issue is fixed in 6571d28b009a5787ef22583137ae11d4b63fb57c.

I'm fixing this problem and others (like the encoding of integers) in my fork https://github.com/PhoneixS/paradoxdriver.

**Comment by leonhad** [comment]
HI,

	I want to ask for apologizes because this week I have no time at all.

	I will merge your suggestions in this weekend with some news features I developing too.

Best regards,
Leonardo Costa

**Comment by PhoneixS** [comment]
Thank you.

If you want, I can make a pull request so you only need to review it.

**Comment by leonhad** [comment]
This is good, I think this is the best form.

I will wait for your pull request.

Um abraço,
Leonardo

2017-08-22 3:02 GMT-03:00 Javier Alfonso <notifications@github.com>:

**Comment by PhoneixS** [comment]
With the pull #11, I think this can be closed. But could be a good option to open another issue for the full implementation.
