### ISSUE TITLE
java.sql.SQLFeatureNotSupportedException: Change properties is not supported yet

### ISSUE THREAD

**Issue by Ferhatos** [leonhad/paradoxdriver#12]
It will be good using Paradox JDBC in SQL client tools like "squirrel" for example.

I need migrate some data from a Paradox database to MySql.
I tried paradox-jdbc in "squirrel" with no succes (see stack trace below) 

Is there any way to read a Paradox database and export it into SQL ?

Thank you for the JDBC, I'll use it in a java program to do the migration if necessary.

`java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.sql.SQLFeatureNotSupportedException: Change properties is not supported yet.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.awaitConnection(OpenConnectionCommand.java:132)
	at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.access$100(OpenConnectionCommand.java:45)
	at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand$2.run(OpenConnectionCommand.java:115)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.sql.SQLFeatureNotSupportedException: Change properties is not supported yet.
	at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.executeConnect(OpenConnectionCommand.java:171)
	at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.access$000(OpenConnectionCommand.java:45)
	at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand$1.run(OpenConnectionCommand.java:104)
	... 5 more
Caused by: java.sql.SQLFeatureNotSupportedException: Change properties is not supported yet.
	at com.googlecode.paradox.ParadoxConnection.<init>(ParadoxConnection.java:98)
	at com.googlecode.paradox.Driver.connect(Driver.java:42)
	at net.sourceforge.squirrel_sql.fw.sql.SQLDriverManager.getConnection(SQLDriverManager.java:133)
	at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.executeConnect(OpenConnectionCommand.java:167)
`

**Comment by leonhad** [comment]
Hi,

Can you tell the driver version you are using and the Squirrel version?

Regards,
Leonardo

2017-09-14 10:10 GMT-03:00 Ferhatos <notifications@github.com>:

**Comment by leonhad** [comment]
Fixed in 1.4.0 version.
