### ISSUE TITLE
Unsupported CLOB block type: 1

### ISSUE THREAD

**Issue by acidg** [leonhad/paradoxdriver#21]
I am getting this error when calling `ClobDescriptor.getClobString()` Any clue, what is going on here?

`java.sql.SQLException: Unsupported CLOB block type: 1
	at com.googlecode.paradox.metadata.BlobTable.readNextBlock(BlobTable.java:361)
	at com.googlecode.paradox.metadata.BlobTable.readBlock(BlobTable.java:322)
	at com.googlecode.paradox.metadata.BlobTable.getData(BlobTable.java:149)
	at com.googlecode.paradox.metadata.BlobTable.read(BlobTable.java:133)
	at com.googlecode.paradox.rowset.ParadoxClob.parse(ParadoxClob.java:243)
	at com.googlecode.paradox.rowset.ParadoxClob.getAsciiStream(ParadoxClob.java:99)
	at com.googlecode.paradox.data.table.value.ClobDescriptor.getClobString(ClobDescriptor.java:63)
...`

**Comment by leonhad** [comment]
Fixed in version 1.5.0.
