### ISSUE TITLE
java.sql.SQLException: No Prepared Statement

### ISSUE THREAD

**Issue by jahswant** [leonhad/paradoxdriver#37]
main._appstart (java line: 58)
java.sql.SQLException: No Prepared Statement
	at com.googlecode.paradox.ParadoxConnection.prepareStatement(ParadoxConnection.java:516)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$166(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$179(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$177(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$178(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$152(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)

**Comment by leonhad** [comment]
Hi jahswant,

The version 1.5.0 do not support PreparedStatement. The next version will do it (1.6.0).

If you like, you can download the source code here, build with command bellow and use it right now:

`mvn package`

The result code will be in `target` folder.

**Comment by jahswant** [comment]
Thanks
